[package]
name = "rustybovich"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
itertools = "0.11.0"
rayon = "1.8.0"
serde = "1.0.188"
serde_json = "1.0.107"
